// A script to test the /api/submit.php contact endpoint
// Usage: node test_contact_api.js [endpoint_url]
// Example: node test_contact_api.js http://localhost:8000/api/submit.php

// Bypass local SSL inspection issues (e.g. from local antivirus like Bitdefender)
process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';

const testEndpoint = async () => {
  // Use user-provided URL or default to localhost
  const url = process.argv[2] || 'https://kalpandco.com/api/submit.php';
  console.log(`\nTesting contact form submission endpoint: ${url}`);

  // Create a FormData payload matching the browser implementation
  const formData = new FormData();
  formData.append('name', 'Test User');
  formData.append('email', 'test@example.com');
  formData.append('message', 'This is a test message generated by test_contact_api.js');

  try {
    const response = await fetch(url, {
      method: 'POST',
      body: formData,
    });

    console.log(`Status: ${response.status} ${response.statusText}`);
    const contentType = response.headers.get('content-type') || '';

    if (contentType.includes('application/json')) {
      const json = await response.json();
      console.log('Response (JSON):', JSON.stringify(json, null, 2));
    } else {
      const text = await response.text();
      console.log('Response (Raw Text):', text.slice(0, 1000));
    }
  } catch (error) {
    console.error('Connection failed:', error.message);
  }
};

testEndpoint();
